api/urls.py
from django.urls import path, include

from . import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.APIRootView = views.ProjectGutenbergAPIRootView
router.register('book', views.BookViewSet)
router.register('bookshelf', views.BookshelfViewSet)
router.register('agent_type', views.AgentTypeViewSet)
router.register('person', views.PersonViewSet)
router.register('resource', views.ResourceViewSet)
router.register('agent', views.AgentViewSet)
router.register('language', views.LanguageViewSet)
router.register('subject', views.SubjectViewSet)

app_name = "api"
urlpatterns = [
    path("", router.get_api_root_view(), name="index"),
    path("", include(router.urls)),
]

gutenberg_api/urls.py
from django.urls import path, include

urlpatterns = [
    path("", include("main.urls")),
    path("api/", include("api.urls")),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('docs/', views.docs, name='docs'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.conf import settings

from api import models
import os


MARKDOWN_FILES = {}


def lazy_load_markdown(path, toc=True, reload=True):
    """
    Use this to keep markdown files in memory.

    :param path: The path to the Markdown file from BASE_DIR
    :param toc: Generation of Table of Contents
    :param reload: Whether to reload the markdown file on every call. Useful for debug.
    """
    if reload or not path in MARKDOWN_FILES:
        with open(path) as f:
            prefix = "[TOC] \n" if toc else ""
            MARKDOWN_FILES[path] = prefix + f.read()


def index(request):
    """
    The Homepage
    """
    template = loader.get_template('main/index.html')
    context = {
        "books": models.Book.objects.all().count(),
        "creators": models.Person.objects.all().count(),
        "bookshelves": models.Bookshelf.objects.all().count(),
        "subjects": models.Subject.objects.all().count(),
        "resources": models.Resource.objects.all().count(),
        "languages": models.Language.objects.all().count(),
    }
    return HttpResponse(template.render(context, request))


def docs(request):
    """
    The Documentation Page
    """
    template = loader.get_template('main/markdown.html')
    markdown_path = os.path.join(settings.BASE_DIR, "docs/README.md")
    lazy_load_markdown(markdown_path)
    return HttpResponse(template.render({"markdown_html": MARKDOWN_FILES[markdown_path]}, request))

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US">

<head>
    <meta charset="UTF-8" />
    <meta name="Description" content="A JSON RESTful api for Project Gutenberg catalogue." />
    <meta name="Keywords" content="Project Gutenberg API RESTful Django" />
    <meta name="Author" content="Gnik Droy" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0,shrink-to-fit=no" />
    <link rel="icon" type="image/x-icon" href="https://i.ibb.co/M1dWcdP/46271.png">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer"
    />
    <script src="{% static 'main/scripts.js' %}"></script>
    {% block head_extra %} {% endblock %}
    <title>{% block title %}Project Gutenberg API{% endblock %}</title>

</head>

<body>

    <header>
        <div class="d-block float-end py-2 px-5">
            <i class="fas fa-sun d-inline-block align-middle px-2" style="font-size:1.2em; color:#dfd33b;"></i>
            <div class="form-check form-switch d-inline-block align-middle">
                <input class="form-check-input align-middle" type="checkbox" id="light_dark_checkbox" checked>
            </div>
            <i class="fas fa-moon d-inline align-middle" style="font-size:1.2em"></i>
        </div>

        <div class="container-fluid text-center">
            <h1 class="display-1 mx-auto py-5">
                <a class="text-decoration-none" href="{% url 'main:index' %}" style="color: inherit;">
                    <i class="fas fa-book-open"></i> Project Gutenberg API
                </a>
            </h1>
            <p class="mx-auto lead"> A RESTful API to access the entire Project Gutenberg catalogue. </p>
        </div>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer>
        <div class="container-fluid text-center mt-5 p-2" style="border-top: 1px solid rgb(121, 121, 121);">
            <p class="font-small m-0">
                <span style="color: #a2a2a2;">© Copyright {% now "Y" %} - </span> No affilation with Project Gutenberg™
            </p>
        </div>
    </footer>

</body>

</html>

main/templates/main/index.html
{% extends 'main/base.html' %} 
{% load humanize %}
{% block content %}
<div class="container-fluid text-center">
    <div class="container text-white">
        <div class="row py-5 g-5">
            <div class="col-md-4">
                <div class="card bg-danger">
                    <div class="card-body">
                        <h5 class="display-4 mb-5">Books</h5>
                        <h1> {{ books | intcomma}} </h1>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card bg-success">
                    <div class="card-body">
                        <h5 class="display-4 mb-5">Creators</h5>
                        <h1> {{ creators | intcomma }} </h1>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card bg-primary">
                    <div class="card-body">
                        <h5 class="display-4 mb-5">Bookshelves</h5>
                        <h1> {{ bookshelves | intcomma }} </h1>
                    </div>
                </div>
            </div>
        </div>

        <div class="row py-5 g-5">
            <div class="col-md-4">
                <div class="card" style="background-color:#ad6cd5;">
                    <div class="card-body">
                        <h5 class="display-4 mb-5">Subjects</h5>
                        <h1> {{ subjects | intcomma }} </h1>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card bg-secondary">
                    <div class="card-body">
                        <h5 class="display-4 mb-5">Resources</h5>
                        <h1> {{ resources | intcomma }} </h1>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card" style="background-color:#8d8847;">
                    <div class="card-body">
                        <h5 class="display-4 mb-5">Languages</h5>
                        <h1> {{ languages | intcomma }} </h1>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <h3 class="mx-auto pt-5">Play with the API</h3>
    <p class="mx-auto lead">
        Use the available browseable API to quickly prototype, or view the documentation.
    </p>
    <div class="p-5">
        <a href="{% url 'api:index' %}" class="btn btn-lg btn-primary m-1"><i class="fas fa-book"></i> &nbsp; Browseable API</a>
        <a href="{% url 'main:docs' %}" class="btn btn-lg btn-primary m-1"><i class="fas fa-book"></i> &nbsp; Documentation</a>
    </div>
</div>
{% endblock %}

main/templates/main/markdown.html
{% extends 'main/base.html' %}
{% load markdown %}
{% load static %}

{% block head_extra %}
    <link rel="stylesheet" href="{% static 'main/code_highlight.css' %}" />
    <link rel="stylesheet" href="{% static 'main/markdown_styles.css' %}" />

    <script src="{% static 'main/markdown_scripts.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container mt-5 pt-5 markdown-container">
        {{ markdown_html | markdown | safe }}
    </div>
{% endblock %}